#! /bin/sh

bspc config border_width 2
bspc config window_gap 2

bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true

# bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a Chromium desktop='^2'
# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off

~/.screenlayout/$(hostname).sh &

NMONITORS=$(xrandr --listactivemonitors | wc -l)
NMONITORS=$((NMONITORS-1))
if [ $(hostname) == 'dodo-pc' ]; then
    if [[ $NMONITORS == 2 ]]; then
        bspc monitor DP-3 -d 1
        bspc monitor HDMI-1 -d 2 3 4 5 6 7 8 9
    else
        bspc monitor -d 1 2 3 4 5 6 7 8 9
    fi
    setxkbmap -model microsoft -layout br
elif [ $(hostname) == 'dodo-laptop' ]; then
    if [[ $NMONITORS == 1 ]]; then
        bspc monitor -d 1 2 3 4 5 6 7 8 9
    else
        bspc monitor eDP1 -d 1
        bspc monitor HDMI1 -d 2 3 4 5 6 7 8 9
    fi
    setxkbmap -model apple -layout us -variant intl
fi

sxhkd &
~/.config/polybar/launch.sh main &
megasync &
nm-applet &
blueman-applet &
xscreensaver &
telegram-desktop &

# stop dunst if it has been started by any application that called notify-send
killall dunst 

# xgetres is an AUR application that allows us to get the values from Xresources
dunst -config ~/.config/dunst/dunstrc \
    -cb "$(xgetres background)" \
    -lb "$(xgetres background)" \
    -nb "$(xgetres background)" \
    -cf "$(xgetres foreground)" \
    -lf "$(xgetres foreground)" \
    -nf "$(xgetres foreground)" \
    -bf "$(xgetres foreground)" \
    -frame_color "$(xgetres foreground)"