[colors.primary]
background = "#000000"
foreground = "#eaeaea"

[cursor]
style = "Beam"

[env]
TERM = "alacritty"

[font]
size = 10.0

[font.normal]
# family = "MesloLGS NF"
# family = "Iosevka Term"
family = "CaskaydiaCove Nerd Font Mono"
style = "Regular"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "N"
mods = "Control|Shift"

[terminal.shell]
program = "/bin/zsh"
