#!/bin/sh

(
	## Configure keyboard
	echo 0
	echo "# Setting keyboard"
	setxkbmap -layout br,us -variant ,intl -option grp:alt_shift_toggle
	xinput list-props "Satechi ST-UCSW3M" | grep "Device Enabled" && setxkbmap -layout us,br -variant intl, -option grp:alt_shift_toggle || setxkbmap -layout br,us -variant ,intl -option grp:alt_shift_toggle

	## Start sxhkd
	# only try to start sxhkd and picom if they're not already running, regardless if starting or restarting bspwm
	# -m is the mode, necessary for non-US keyboards
	echo 10
	echo "# Starting sxhkd"
	pgrep -x sxhkd >/dev/null || sxhkd -m 1 &

	## Load colors
	echo 20
	echo "# Loading colors"
	wal -R
	. "$HOME/.cache/wal/colors.sh"

	## Config monitors
	# stop polybar if it has been started by any application that called notify-send
	echo 30
	echo "# Stopping polybar"
	polybar-msg cmd quit
	while pgrep -x polybar >/dev/null; do sleep 0.2; done

	echo 40
	echo "# Detecting monitors"
	# grab number of active monitors and name of first monitor
	NMONITORS=$(xrandr --listactivemonitors | tail +2 | wc -l)
	# Store xrandr output once to avoid multiple executions (POSIX compatible)
	mon1=""
	mon1_size=""
	mon2=""
	mon2_size=""
	i=0
	xrandr --listactivemonitors | tail -n +2 | while read -r _ mon_size mon_name _; do
		if [ $i -eq 0 ]; then
			mon1="$mon_name"
			mon1_size=$(echo "$mon_size" | cut -d'x' -f1)
		elif [ $i -eq 1 ]; then
			mon2="$mon_name"
			mon2_size=$(echo "$mon_size" | cut -d'x' -f1)
		fi
		i=$((i + 1))
	done

	echo 50
	echo "# Configuring monitors"
	# Configure monitors
	if [ "$NMONITORS" -ge 2 ]; then
		if [ "$mon1_size" -gt "$mon2_size" ]; then
			BIGMONITOR=$mon1
			SMALLMONITOR=$mon2
		else
			BIGMONITOR=$mon2
			SMALLMONITOR=$mon1
		fi

		bspc monitor "$BIGMONITOR" -d 1 2 3 4 5 6 7 8
		bspc monitor "$SMALLMONITOR" -d 9
	else
		bspc monitor -d 1 2 3 4 5 6 7 8 9
	fi

	## Config bspwm
	echo 60
	echo "# Configuring bspwm"
	# Set the border colors.
	bspc config normal_border_color "$color1"
	bspc config active_border_color "$color2"
	bspc config focused_border_color "$color15"
	bspc config presel_feedback_color "$color1"

	bspc config border_width 1

	bspc config automatic_scheme alternate
	bspc config split_ratio 0.5
	bspc config borderless_monocle true
	bspc config gapless_monocle true
	bspc config single_monocle true
	bspc config remove_disabled_monitors true
	bspc config remove_unplugged_monitors true
	bspc config merge_overlapping_monitors true

	## Launch polybar in all displays
	echo 70
	echo "# Starting polybar"
	for mon in $(bspc query -M --names); do
		for bar in the_bar_left the_bar_right the_bar_center; do
			MONITOR=$mon polybar --reload $bar 2>&1 | tee -a /tmp/polybar_${mon}_${bar}.log &
			disown
		done
	done

	## Config screen layout
	echo 80
	echo "# Configuring screen layout"
	if [[ $1 -eq 0 ]]; then
		${XDG_CONFIG_HOME}/screenlayout.sh
	fi

	## Start applications
	# Helper function to start an app if not running and notify
	start_app() {
		local app_name="$1"
		local start_cmd="$2"
		local notify_name="${3:-$app_name}"

		if pgrep -x "$app_name" >/dev/null; then
			notify-send "$notify_name is already running."
		else
			$start_cmd &
			sleep 1
			if pgrep -x "$app_name" >/dev/null; then
				notify-send "$notify_name started successfully."
			else
				notify-send "Failed to start $notify_name."
			fi
		fi
	}

	echo 90
	echo "# Starting applications"
	start_app "picom" "picom --config $XDG_CONFIG_HOME/picom.conf" &
	start_app "nm-applet" "nm-applet" &
	start_app "blueman-applet" "blueman-applet" &
	start_app "unclutter" "unclutter" &

	# Applications that should only be started once
	if [[ $1 -eq 0 ]]; then
		start_app "mega-sync" "mega-sync" &
		# start_app "Discord" "discord"
	fi

	echo 100
	echo "# Finished"
	sleep 2
) | yad --progress \
	--fixed \
	--enable-log="Startup events" \
	--text="Initializing bspwm..." \
	--button=yad-cancel \
	--log-expanded \
	--auto-kill \
	--width=400
